#ifndef ISR80H_H
#define ISR80H_H

enum SystemCommands
{
    SYSTEM_COMMAND0_SUM,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_OPEN,
    SYSTEM_COMMAND3_READ,
    SYSTEM_COMMAND4_FORK,
    SYSTEM_COMMAND5_EXIT,
    SYSTEM_COMMAND6_READLINE,
    SYSTEM_COMMAND7_WRITE,
    SYSTEM_COMMAND8_DELETE,
    SYSTEM_COMMAND9_CLOSE,
    SYSTEM_COMMAND10_READDIR,
    SYSTEM_COMMAND11_WAIT,
};

void isr80h_register_commands();

#endif